class AzureDevOpsGenerator {
  static generate(config) {
    const {
      projectName,
      repositoryUrl,
      branch = 'main',
      dockerImage,
      environmentVariables = {},
      testCommand = 'npm test',
      buildCommand = 'npm run build',
      deployCommand,
      azureSubscription,
      resourceGroup,
      appName
    } = config;

    let azurePipeline = `# Azure DevOps Pipeline for ${projectName}
# Generated by DevOps Pipeline Generator

trigger:
  branches:
    include:
    - ${branch}
  paths:
    exclude:
    - README.md
    - docs/

pr:
  branches:
    include:
    - ${branch}

pool:
  vmImage: 'ubuntu-latest'

variables:
  projectName: '${projectName}'
  buildConfiguration: 'Release'
  dockerImage: '${dockerImage || '${ACR_NAME}/${projectName}'}'
  azureSubscription: '${azureSubscription || 'Azure Service Connection'}'
  resourceGroup: '${resourceGroup || 'rg-${projectName}'}'
  appName: '${appName || 'app-${projectName}'}'
`;

    // Add environment variables
    if (Object.keys(environmentVariables).length > 0) {
      azurePipeline += '\n  # Environment variables\n';
      Object.entries(environmentVariables).forEach(([key, value]) => {
        azurePipeline += `  ${key.toUpperCase()}: ${value}\n`;
      });
    }

    azurePipeline += `
stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: Build
    displayName: 'Build Job'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '18.x'
      displayName: 'Install Node.js'

    - task: Npm@1
      displayName: 'Install Dependencies'
      inputs:
        command: 'ci'
        verbose: false

    - task: Npm@1
      displayName: 'Run Tests'
      inputs:
        command: 'custom'
        customCommand: '${testCommand}'

    - task: PublishCodeCoverageResults@1
      displayName: 'Publish Code Coverage'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: '$(System.DefaultWorkingDirectory)/coverage/cobertura-coverage.xml'
      condition: succeededOrFailed()

    - task: Npm@1
      displayName: 'Build Application'
      inputs:
        command: 'custom'
        customCommand: '${buildCommand}'

    - task: CopyFiles@2
      displayName: 'Copy Build Files'
      inputs:
        SourceFolder: '$(System.DefaultWorkingDirectory)'
        Contents: |
          dist/**/*
          build/**/*
          package.json
        TargetFolder: '$(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Build Artifacts'
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'

- stage: Docker
  displayName: 'Docker Build and Push'
  dependsOn: Build
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/${branch}'))
  jobs:
  - job: Docker
    displayName: 'Docker Job'
    steps:
    - task: DownloadBuildArtifacts@1
      displayName: 'Download Build Artifacts'
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'

    - task: Docker@2
      displayName: 'Build Docker Image'
      inputs:
        command: 'build'
        dockerfile: '**/Dockerfile'
        repository: '$(dockerImage)'
        tags: |
          $(Build.BuildId)
          latest

    - task: Docker@2
      displayName: 'Push to ACR'
      inputs:
        command: 'push'
        repository: '$(dockerImage)'
        tags: |
          $(Build.BuildId)
          latest
        containerRegistry: '$(azureSubscription)'

- stage: SecurityScan
  displayName: 'Security Scanning'
  dependsOn: Build
  jobs:
  - job: Security
    displayName: 'Security Scan Job'
    steps:
    - task: SnykSecurityScan@1
      displayName: 'Snyk Security Scan'
      inputs:
        serviceConnectionEndpoint: 'Snyk Service Connection'
        testType: 'app'
        severityThreshold: 'high'
        failOnThreshold: true

    - task: ContainerScan@0
      displayName: 'Container Vulnerability Scan'
      inputs:
        imageRepository: '$(dockerImage):$(Build.BuildId)'
        azureSubscription: '$(azureSubscription)'

- stage: DeployStaging
  displayName: 'Deploy to Staging'
  dependsOn:
  - Docker
  - SecurityScan
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/${branch}'))
  jobs:
  - deployment: DeployStaging
    displayName: 'Deploy to Staging'
    environment: 'staging'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            displayName: 'Download Build Artifacts'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App (Staging)'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webAppLinux'
              appName: '$(appName)-staging'
              package: '$(System.ArtifactsDirectory)/drop'

          - task: AzureAppServiceSettings@1
            displayName: 'Configure App Settings'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: '$(appName)-staging'
              resourceGroupName: '$(resourceGroup)'
              appSettings: |
                [
                  {
                    "name": "NODE_ENV",
                    "value": "staging",
                    "slotSetting": false
                  },
                  {
                    "name": "BUILD_ID",
                    "value": "$(Build.BuildId)",
                    "slotSetting": false
                  }
                ]

- stage: DeployProduction
  displayName: 'Deploy to Production'
  dependsOn: DeployStaging
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/${branch}'))
  jobs:
  - deployment: DeployProduction
    displayName: 'Deploy to Production'
    environment: 'production'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: DownloadBuildArtifacts@1
            displayName: 'Download Build Artifacts'
            inputs:
              buildType: 'current'
              downloadType: 'single'
              artifactName: 'drop'
              downloadPath: '$(System.ArtifactsDirectory)'

          - task: AzureWebApp@1
            displayName: 'Deploy to Azure Web App (Production)'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appType: 'webAppLinux'
              appName: '$(appName)-production'
              package: '$(System.ArtifactsDirectory)/drop'

          - task: AzureAppServiceSettings@1
            displayName: 'Configure App Settings'
            inputs:
              azureSubscription: '$(azureSubscription)'
              appName: '$(appName)-production'
              resourceGroupName: '$(resourceGroup)'
              appSettings: |
                [
                  {
                    "name": "NODE_ENV",
                    "value": "production",
                    "slotSetting": false
                  },
                  {
                    "name": "BUILD_ID",
                    "value": "$(Build.BuildId)",
                    "slotSetting": false
                  }
                ]

          - task: AzureCLI@2
            displayName: 'Swap Slots'
            inputs:
              azureSubscription: '$(azureSubscription)'
              scriptType: 'bash'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az webapp deployment slot swap \\
                  --resource-group $(resourceGroup) \\
                  --name $(appName)-production \\
                  --slot staging \\
                  --target-slot production

- stage: Notify
  displayName: 'Notifications'
  dependsOn:
  - DeployProduction
  condition: always()
  jobs:
  - job: Notify
    displayName: 'Send Notifications'
    steps:
    - task: NotifySlack@1
      displayName: 'Send Slack Notification'
      inputs:
        slackEndpoint: '$(SLACK_WEBHOOK_URL)'
        message: |
          Pipeline Status: $(Agent.JobStatus)
          Project: $(projectName)
          Build: $(Build.BuildNumber)
          Commit: $(Build.SourceVersion)
          Branch: $(Build.SourceBranch)
`;

    return azurePipeline;
  }

  static getTemplate() {
    return {
      name: 'Azure DevOps Pipeline Generator',
      description: 'Generate Azure DevOps pipeline configuration with multi-stage deployment',
      fields: [
        {
          name: 'projectName',
          label: 'Project Name',
          type: 'text',
          required: true,
          placeholder: 'my-awesome-project'
        },
        {
          name: 'repositoryUrl',
          label: 'Repository URL',
          type: 'text',
          required: true,
          placeholder: 'https://dev.azure.com/org/project/_git/repo'
        },
        {
          name: 'branch',
          label: 'Main Branch',
          type: 'text',
          defaultValue: 'main',
          placeholder: 'main or master'
        },
        {
          name: 'dockerImage',
          label: 'Docker Image Name',
          type: 'text',
          placeholder: 'myacr.azurecr.io/project',
          description: 'Full Docker image name including ACR'
        },
        {
          name: 'azureSubscription',
          label: 'Azure Subscription Service Connection',
          type: 'text',
          placeholder: 'Azure Service Connection Name',
          description: 'Name of your Azure service connection in Azure DevOps'
        },
        {
          name: 'resourceGroup',
          label: 'Resource Group',
          type: 'text',
          placeholder: 'rg-my-project',
          description: 'Azure resource group name'
        },
        {
          name: 'appName',
          label: 'App Service Name',
          type: 'text',
          placeholder: 'app-my-project',
          description: 'Azure App Service name'
        },
        {
          name: 'testCommand',
          label: 'Test Command',
          type: 'text',
          defaultValue: 'npm test',
          placeholder: 'npm test or pytest'
        },
        {
          name: 'buildCommand',
          label: 'Build Command',
          type: 'text',
          defaultValue: 'npm run build',
          placeholder: 'npm run build or mvn package'
        },
        {
          name: 'environmentVariables',
          label: 'Environment Variables',
          type: 'keyvalue',
          placeholder: 'NODE_ENV=production\nAPI_URL=https://api.example.com'
        }
      ]
    };
  }
}

module.exports = AzureDevOpsGenerator;
