class GitLabCIGenerator {
  static generate(config) {
    const {
      projectName,
      repositoryUrl,
      branch = 'main',
      dockerImage,
      environmentVariables = {},
      testCommand = 'npm test',
      buildCommand = 'npm run build',
      deployCommand
    } = config;

    let gitlabCi = `# CI/CD Pipeline for ${projectName}
# Generated by DevOps Pipeline Generator

stages:
  - test
  - build
  - docker
  - deploy

variables:
  PROJECT_NAME: ${projectName}
  NODE_VERSION: "18"
  DOCKER_IMAGE: ${dockerImage || '${CI_REGISTRY_USER}/${PROJECT_NAME}'}
`;

    // Add environment variables
    if (Object.keys(environmentVariables).length > 0) {
      gitlabCi += '\n  # Environment variables\n';
      Object.entries(environmentVariables).forEach(([key, value]) => {
        gitlabCi += `  ${key.toUpperCase()}: ${value}\n`;
      });
    }

    gitlabCi += `
# Cache configuration
cache:
  key: \${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - .npm/

# Test stage
test:
  stage: test
  image: node:\${NODE_VERSION}
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - ${testCommand}
  coverage: '/All files[^|]*\\|[^|]*\\s+([\\d\\.]+)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage/cobertura-coverage.xml
    paths:
      - coverage/
    expire_in: 1 week
  only:
    - branches
    - merge_requests

# Build stage
build:
  stage: build
  image: node:\${NODE_VERSION}
  dependencies:
    - test
  before_script:
    - npm ci --cache .npm --prefer-offline
  script:
    - ${buildCommand}
  artifacts:
    paths:
      - dist/
      - build/
    expire_in: 1 week
  only:
    - branches

# Docker build stage
docker:
  stage: docker
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  dependencies:
    - build
  before_script:
    - echo \${CI_REGISTRY_PASSWORD} | docker login -u \${CI_REGISTRY_USER} --password-stdin \${CI_REGISTRY}
  script:
    - docker build -t \${DOCKER_IMAGE}:\${CI_COMMIT_SHORT_SHA} .
    - docker tag \${DOCKER_IMAGE}:\${CI_COMMIT_SHORT_SHA} \${DOCKER_IMAGE}:latest
    - docker push \${DOCKER_IMAGE}:\${CI_COMMIT_SHORT_SHA}
    - docker push \${DOCKER_IMAGE}:latest
  only:
    - ${branch}
  when: manual

# Security scanning
sast:
  stage: test
  include:
    - template: Security/SAST.gitlab-ci.yml
  only:
    - branches
    - merge_requests

dependency_scanning:
  stage: test
  include:
    - template: Security/Dependency-Scanning.gitlab-ci.yml
  only:
    - branches
    - merge_requests

container_scanning:
  stage: docker
  include:
    - template: Security/Container-Scanning.gitlab-ci.yml
  variables:
    CI_APPLICATION_REPOSITORY: \${DOCKER_IMAGE}
    CI_APPLICATION_TAG: \${CI_COMMIT_SHORT_SHA}
  only:
    - ${branch}
  needs:
    - docker

# Deploy to staging
deploy_staging:
  stage: deploy
  image: alpine:latest
  dependencies:
    - docker
  before_script:
    - apk add --no-cache curl
  script:
    - echo "Deploying to staging environment..."
    - curl -X POST \${STAGING_WEBHOOK_URL} -H "Content-Type: application/json" -d '{"image":"\${DOCKER_IMAGE}:\${CI_COMMIT_SHORT_SHA}"}'
  environment:
    name: staging
    url: https://staging.\${PROJECT_NAME}.com
  only:
    - ${branch}
  when: manual

# Deploy to production
deploy_production:
  stage: deploy
  image: alpine:latest
  dependencies:
    - docker
  before_script:
    - apk add --no-cache curl
  script:
    - echo "Deploying to production environment..."
    - curl -X POST \${PRODUCTION_WEBHOOK_URL} -H "Content-Type: application/json" -d '{"image":"\${DOCKER_IMAGE}:\${CI_COMMIT_SHORT_SHA}"}'
  environment:
    name: production
    url: https://\${PROJECT_NAME}.com
  only:
    - ${branch}
  when: manual
  allow_failure: false

# Notification on failure
notify_failure:
  stage: deploy
  image: alpine:latest
  script:
    - |
      curl -X POST "\${SLACK_WEBHOOK_URL}" \\
        -H 'Content-Type: application/json' \\
        -d '{
          "text": "Pipeline Failed: \${CI_PROJECT_NAME}",
          "blocks": [
            {
              "type": "section",
              "text": {
                "type": "mrkdwn",
                "text": "*Pipeline Failed*\\n*Project:* \${CI_PROJECT_NAME}\\n*Branch:* \${CI_COMMIT_REF_NAME}\\n*Commit:* \${CI_COMMIT_SHORT_SHA}\\n*Author:* \${GITLAB_USER_NAME}\\n*Pipeline:* \${CI_PIPELINE_URL}"
              }
            }
          ]
        }'
  when: on_failure
  only:
    - ${branch}
`;

    return gitlabCi;
  }

  static getTemplate() {
    return {
      name: 'GitLab CI Generator',
      description: 'Generate GitLab CI/CD pipeline configuration with best practices',
      fields: [
        {
          name: 'projectName',
          label: 'Project Name',
          type: 'text',
          required: true,
          placeholder: 'my-awesome-project'
        },
        {
          name: 'repositoryUrl',
          label: 'Repository URL',
          type: 'text',
          required: true,
          placeholder: 'https://gitlab.com/username/project'
        },
        {
          name: 'branch',
          label: 'Main Branch',
          type: 'text',
          defaultValue: 'main',
          placeholder: 'main or master'
        },
        {
          name: 'dockerImage',
          label: 'Docker Image Name',
          type: 'text',
          placeholder: 'registry.gitlab.com/username/project',
          description: 'Full Docker image name including registry'
        },
        {
          name: 'testCommand',
          label: 'Test Command',
          type: 'text',
          defaultValue: 'npm test',
          placeholder: 'npm test or pytest'
        },
        {
          name: 'buildCommand',
          label: 'Build Command',
          type: 'text',
          defaultValue: 'npm run build',
          placeholder: 'npm run build or mvn package'
        },
        {
          name: 'deployCommand',
          label: 'Deploy Command',
          type: 'textarea',
          placeholder: 'kubectl apply -f k8s/',
          description: 'Custom deployment commands (optional)'
        },
        {
          name: 'environmentVariables',
          label: 'Environment Variables',
          type: 'keyvalue',
          placeholder: 'NODE_ENV=production\nAPI_URL=https://api.example.com'
        }
      ]
    };
  }
}

module.exports = GitLabCIGenerator;
