class PythonGenerator {
  generate(config) {
    const {
      scriptName = 'script',
      description = '',
      pythonVersion = '3.8',
      encoding = 'utf-8',
      logging = true,
      errorHandling = true,
      mainFunction = true,
      imports = [],
      functions = [],
      mainLogic = [],
      dependencies = []
    } = config;

    // Handle imports that might come as string from textarea
    const processedImports = Array.isArray(imports) 
      ? imports 
      : (typeof imports === 'string' ? imports.split('\n').filter(imp => imp.trim()) : []);

    // Handle dependencies that might come as string from textarea
    const processedDependencies = Array.isArray(dependencies) 
      ? dependencies 
      : (typeof dependencies === 'string' ? dependencies.split('\n').filter(dep => dep.trim()) : []);

    // Handle mainLogic that might come as string from textarea
    const processedMainLogic = Array.isArray(mainLogic) 
      ? mainLogic 
      : (typeof mainLogic === 'string' ? mainLogic.split('\n').filter(cmd => cmd.trim()) : []);

    // Handle functions that might come as string from textarea
    let processedFunctions = functions;
    if (typeof functions === 'string') {
      try {
        processedFunctions = JSON.parse(functions);
      } catch (e) {
        processedFunctions = [];
      }
    }

    let script = '';

    // Shebang
    script += '#!/usr/bin/env python3\n\n';

    // Encoding declaration
    script += `# -*- coding: ${encoding} -*-\n\n`;

    // Description
    if (description) {
      script += `"""\n${description}\n\n`;
      script += `Generated by DevOps Pipeline Generator\n`;
      script += `Python Version: ${pythonVersion}+\n`;
      script += '"""\n\n';
    }

    // Imports
    if (processedImports.length > 0) {
      script += '# Imports\n';
      processedImports.forEach(imp => {
        script += `import ${imp}\n`;
      });
      script += '\n';
    }

    // Standard imports based on features
    let standardImports = [];
    if (logging) standardImports.push('logging');
    if (errorHandling) standardImports.push('sys');
    if (processedDependencies.length > 0) standardImports.push('subprocess');

    // Add standard imports if not already present
    standardImports.forEach(imp => {
      if (!processedImports.includes(imp)) {
        script += `import ${imp}\n`;
      }
    });

    if (standardImports.length > 0) {
      script += '\n';
    }

    // Logging configuration
    if (logging) {
      script += '# Configure logging\n';
      script += 'logging.basicConfig(\n';
      script += '    level=logging.INFO,\n';
      script += '    format=\'%(asctime)s - %(levelname)s - %(message)s\',\n';
      script += '    handlers=[\n';
      script += '        logging.StreamHandler(sys.stdout)\n';
      script += '    ]\n';
      script += ')\n';
      script += 'logger = logging.getLogger(__name__)\n\n';
    }

    // Dependencies check
    if (processedDependencies.length > 0) {
      script += '# Check dependencies\n';
      script += 'def check_dependencies():\n';
      processedDependencies.forEach(dep => {
        script += `    try:\n`;
        script += `        import ${dep}\n`;
        script += `    except ImportError:\n`;
        script += `        logger.error(f"Error: {dep} is not installed")\n`;
        script += `        sys.exit(1)\n`;
      });
      script += '\n';
    }

    // Functions
    if (processedFunctions.length > 0) {
      script += '# Functions\n';
      processedFunctions.forEach(func => {
        script += `def ${func.name}():\n`;
        if (func.description) {
          script += `    """${func.description}"""\n`;
        }
        if (func.args && func.args.length > 0) {
          script += `    def ${func.name}(${func.args.join(', ')}):\n`;
        }
        func.body.split('\n').forEach(line => {
          if (line.trim()) {
            script += `    ${line}\n`;
          }
        });
        script += '\n\n';
      });
    }

    // Main function
    if (mainFunction) {
      script += 'def main():\n';
      script += '    """Main execution function"""\n';
      
      if (processedDependencies.length > 0) {
        script += '    # Check dependencies\n';
        script += '    check_dependencies()\n\n';
      }

      if (logging) {
        script += '    logger.info("Starting script execution")\n\n';
      }

      // Main logic
      processedMainLogic.forEach(command => {
        if (command.trim()) {
          if (logging && command.trim()) {
            script += `    logger.info("Executing: ${command.replace(/"/g, '\\"')}")\n`;
          }
          script += `    ${command}\n`;
        }
      });

      if (logging) {
        script += '\n    logger.info("Script completed successfully")\n';
      }

      script += '\n';
    }

    // Entry point
    if (mainFunction) {
      script += 'if __name__ == "__main__":\n';
      script += '    main()\n';
    } else {
      script += '# Direct execution\n';
      if (processedDependencies.length > 0) {
        script += 'check_dependencies()\n';
      }
      if (logging) {
        script += 'logger.info("Starting script execution")\n';
      }
      processedMainLogic.forEach(command => {
        if (command.trim()) {
          script += `${command}\n`;
        }
      });
      if (logging) {
        script += 'logger.info("Script completed successfully")\n';
      }
    }

    return script;
  }

  getTemplate() {
    return {
      name: 'Python Script Generator',
      description: 'Generate Python scripts with proper structure, logging, error handling, and dependency management',
      fields: [
        {
          name: 'scriptName',
          label: 'Script Name',
          type: 'text',
          required: true,
          placeholder: 'my_script',
          description: 'Name of the script file (snake_case)'
        },
        {
          name: 'description',
          label: 'Description',
          type: 'textarea',
          placeholder: 'This script automates data processing tasks',
          description: 'Brief description of what the script does'
        },
        {
          name: 'pythonVersion',
          label: 'Python Version',
          type: 'select',
          defaultValue: '3.8',
          options: [
            { value: '3.8', label: '3.8+ - Minimum for modern features' },
            { value: '3.9', label: '3.9+ - Enhanced features' },
            { value: '3.10', label: '3.10+ - Pattern matching' },
            { value: '3.11', label: '3.11+ - Latest improvements' }
          ],
          description: 'Minimum Python version requirement'
        },
        {
          name: 'encoding',
          label: 'Encoding',
          type: 'text',
          defaultValue: 'utf-8',
          placeholder: 'utf-8',
          description: 'Source file encoding'
        },
        {
          name: 'logging',
          label: 'Enable Logging',
          type: 'checkbox',
          defaultValue: true,
          description: 'Add logging functionality to the script'
        },
        {
          name: 'errorHandling',
          label: 'Enable Error Handling',
          type: 'checkbox',
          defaultValue: true,
          description: 'Add error handling and exit on errors'
        },
        {
          name: 'mainFunction',
          label: 'Use Main Function',
          type: 'checkbox',
          defaultValue: true,
          description: 'Wrap main logic in a main() function'
        },
        {
          name: 'imports',
          label: 'Imports',
          type: 'textarea',
          placeholder: 'os\njson\nrequests',
          description: 'Python modules to import (one per line)'
        },
        {
          name: 'dependencies',
          label: 'Dependencies',
          type: 'textarea',
          placeholder: 'requests\npandas\nnumpy',
          description: 'Python packages that must be installed (one per line)'
        },
        {
          name: 'functions',
          label: 'Functions',
          type: 'json',
          placeholder: '[{"name": "process_data", "description": "Process input data", "args": ["data"], "body": "return data.strip()"}]',
          description: 'JSON array of functions with name, description, args, and body'
        },
        {
          name: 'mainLogic',
          label: 'Main Logic',
          type: 'textarea',
          placeholder: 'print("Starting process")\ndata = read_file("input.txt")\nprocess_data(data)',
          description: 'Main script logic (one per line)'
        }
      ]
    };
  }
}

module.exports = new PythonGenerator();
