version: "3.9"

services:
  frontend:
    image: awsmallick1999/infrapilot-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "3000:80"
    networks:
      - app-network

  backend:
    image: awsmallick1999/infrapilot-backend:latest
    container_name: backend
    restart: always
    ports:
      - "5001:5001"
    environment:
      - GOOGLE_CLIENT_ID=826989147293-ofpofmqf6rk5e0g98kk5qsn0onsf3mr6.apps.googleusercontent.com
      - GOOGLE_CLIENT_SECRET=YOUR_GOOGLE_CLIENT_SECRET_HERE
      - GITHUB_CLIENT_ID=YOUR_GITHUB_CLIENT_ID_HERE
      - GITHUB_CLIENT_SECRET=YOUR_GITHUB_CLIENT_SECRET_HERE
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge