version: "3.9"

services:

  frontend:
    image: awsmallick1999/infrapilot-frontend:latest
    container_name: frontend
    restart: always
    ports:
      - "3000:3000"

  backend:
    image: awsmallick1999/infrapilot-backend:latest
    container_name: backend
    restart: always
    ports:
      - "5001:5001"

    env_file:
      - .env