apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: Opaque
stringData:
  mongodb-uri: "mongodb+srv://chinmayakumarmallick25_db_user:vphFFVCHD1mdX5z5@cluster0.pjtae8z.mongodb.net/issue-tracker?retryWrites=true&w=majority"
  jwt-secret: "your-super-secret-jwt-key-change-this-in-production"